import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GoogleOAuthProvider } from "@react-oauth/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GoogleOAuthProvider clientId="112101758329-m6tvjuh0ch1rdldpe42ledn0ic69fi94.apps.googleusercontent.com">
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </GoogleOAuthProvider>
  );
}
